default:
  before_script:
    - cd ./pyreccaster/
  cache:
    paths:
      - .venv
      - .cargo/bin
      - .cargo/registry/index
      - .cargo/registry/cache
      - target/debug/deps
      - target/debug/build

variables:
    CARGO_HOME: "$CI_PROJECT_DIR/.cargo"
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

stages:
  - build
  - publish

build:
  stage: build
  image: 
    name: ghcr.io/pyo3/maturin:latest
    entrypoint: [""]
  environment:
    name: $TARGET
  parallel:
    matrix:
      - TARGET: ["x86_64-pc-windows-gnu", "x86_64-unknown-linux-gnu", "x86_64-apple-darwin"]
  script:
    - python -m venv venv
    - source venv/bin/activate
    - pip install ziglang
    - rustup target add $TARGET
    - maturin build --release --interpreter python3.9 --target $TARGET --zig
  artifacts:
    when: on_success
    paths:
      - target/wheels/*.whl

publish:
  stage: publish
  needs: ["build"]
  image: 
    name: ghcr.io/pyo3/maturin:main
    entrypoint: [""]

# - maturin publish --non-interactive --skip-existing --username ${CI_JOB_TOKEN} --password gitlab-ci-token --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi
  script:
    - maturin publish --non-interactive --skip-existing --username ${CI_JOB_TOKEN} --password gitlab-ci-token
